#!/usr/bin/env ruby -I lib -w

require 'environment'

class SpaceWars < Controller

  on "w" do
    spaceship.size *= 1.1
  end

  on "s" do
    spaceship.size *= 0.9
  end

  on "=" do
    $camera.zoom_in
  end

  on "-" do
    $camera.zoom_out
  end

  on "k" do
    # camera.offset_x += 0.01
  end

  on "q" do
    exit
  end

  def spaceship
    @spaceship ||= Spaceship.new
  end

  def on_tick
    spaceship.animate
  end

end


class Spaceship

  attr_accessor :size

  def initialize
    @size = 0.5
  end

  def animate
    rotator.yaw!(0.01)
    rotator.pitch!(-0.01)
    rotator.roll!(0.02)
  end

  def rotation
    rotator.matrix
  end

  private

  def rotator
    @rotator ||= Rotator.new
  end

end


class Fuselage < View

  def draw
    glMultMatrix(@model.rotation)

    glColor(1, 0, 0)
    glutSolidTeapot @model.size
  end

end

class Camera

  # XXX this is wrong
  def zoom_in
    rotator.translate(0, 0, 0.01)
  end

  # XXX this is wrong
  def zoom_out
    rotator.translate(0, 0, -0.01)
  end

  def rotation
    rotator.matrix.inverse
  end

  private

  def rotator
    @rotator ||= Rotator.new
  end

end

class CameraView < View

  def draw!
    glMultMatrix(@model.rotation)
  end

end

space_wars = SpaceWars.new
window = Window.new(space_wars)

$camera = Camera.new

window.views << CameraView.new($camera)
window.views << Fuselage.new(space_wars.spaceship)

window.start
