#!/usr/bin/env ruby -I lib -w

require 'socket'

address = "localhost"
dts = TCPServer.new(address, 31337)

Thread.abort_on_exception=true

@clients = []
@client_names = []

@client_matrix = []
loop do
  Thread.start(dts.accept) do |s|
    @clients << s

    client_number = @client_names.size

    while(line = s.gets)
      command, info = line.split(': ')
      info.chomp!

      if command == "get"
        requested_id = @client_names.index(info)
        s.puts @client_matrix[requested_id]
      end

      if command == "matrix"
        @client_matrix[client_number]  = info
        p client_number
      end

      if command == "set_name"
        client_number = @client_names.index(info) || @client_names.size
        @client_names[client_number] = info
      end

      if command == "request"
        s.puts @client_matrix[client_number] if info == "matrix"
        s.puts "#{@client_names}"            if info == "players"
      end
    end

    s.close
  end
end
