#!/usr/bin/env ruby -I lib -w

require 'socket'

dts = TCPServer.new('192.168.0.101', 31337)

Thread.abort_on_exception=true

@clients = []
@client_names = []

@client_matrix = []
loop do
  Thread.start(dts.accept) do |s|
    client_number = @clients.size
    @clients << s

    while(line = s.gets)
      command, info = line.split(': ')
      info.chomp!

      @client_matrix << info               if command == "matrix"
      @client_names[client_number] = info  if command == "set_name"

      if command == "request"
        s.puts @client_matrix[client_number] if info == "matrix"
        s.puts "#{@client_names}"            if info == "players"
      end
    end

    s.close
  end
end
